### ISSUE TITLE
ConnectionError: Bad Status Line("' '",)

### ISSUE THREAD

**Issue by sbjaved** [fm4d/KickassAPI#6]
My code was running fine for past week but today it suddenly started throwing up errors.

Traceback (most recent call last):
  File "/home/saad/Code/kat.py", line 102, in <module>
    main()
  File "/home/saad/Code/kat.py", line 78, in main
    for torrent in Search(film).category(CATEGORY.MOVIES).order(ORDER.SEED):
  File "/usr/local/lib/python2.7/dist-packages/KickassAPI.py", line 182, in _items
    torrents = map(self._get_torrent, self._get_rows())
  File "/usr/local/lib/python2.7/dist-packages/KickassAPI.py", line 228, in _get_rows
    pq = PyQuery(url=self.url.build())
  File "/usr/local/lib/python2.7/dist-packages/pyquery/pyquery.py", line 194, in __init__
    html = url_opener(url, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyquery/openers.py", line 71, in url_opener
    return _requests(url, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyquery/openers.py", line 56, in _requests
    resp = meth(url=url, **kw)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 599, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 192, in resolve_redirects
    allow_redirects=False,
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

Please take a look.

**Comment by reduxionist** [comment]
This is error is not coming from the python API. The ConnectionError you encountered was due to a network connectivity issue, not a programming error. You will see this error from time to time when using the requests library in many projects whenever your Internet connection is flaky, the server is overloaded, &etc. If you want to add nicer error handling, feel free to submit a pull request wrapping the pyquery calls with try-except blocks for this requests exception, but personally I consider this a standard error to encounter -- there's nothing useful the API can do for you if your network connectivity isn't working for some reason (well, I suppose you could retry, perhaps with exponential back-off, but since the specifics would vary based on the user's situation I still think it's not a necessarily the API's part to play this role).

Hope that helps explain it, but if you have any questions feel free to ask of course!

**Comment by fm4d** [comment]
Well answered, closing this issue.

**Comment by sbjaved** [comment]
Thank you for your response. You're correct in that it turned out to be a
network issue. I suppose I should've paid more attention to the code than
filing a frivolous bug report. My apologies ☺

Regards,
Saad
